name: Build and Deploy
on:
  push:
    branches:
      - main # ou o nome do seu branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install # ou qualquer outro comando para instalar dependências

      - name: Build Application
        run: npm run build # ou qualquer outro comando para construir seu aplicativo

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "nome-do-seu-aplicativo-no-heroku"
